language: node_js
node_js:
  - "node"
  - "8"
sudo: false

cache:
  npm: true
  directories:
    - node_modules

before_install:
  - npm install codecov -g

install:
  - npm install

before_script:
  - tsc -p . --sourcemap

script:
  - npm run test
  - npm run lint

after_success:
  - codecov